{% set name = "stac-geoparquet" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/stac_geoparquet-{{ version }}.tar.gz
  sha256: 7a3de5b0b36f1d4cf2e522a23ce36c5570e290753e5b93cc9d7cad8da8b60b09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - pc-geoparquet = stac_geoparquet.cli:main

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - ciso8601
    - deltalake
    - geopandas
    - packaging
    - pandas
    - pyarrow >=16
    - pyproj
    - pystac
    - python >=3.8
    - shapely
    - orjson
    - typing-extensions

test:
  imports:
    - stac_geoparquet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/stac-geoparquet/
  summary: stac-geoparquet
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
    - TomAugspurger
