{% set name = "stac-geoparquet" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stac_geoparquet-{{ version }}.tar.gz
  sha256: 191203fabe6a8a3478f61cf0b465356ebb5757c16b79da13286505d8223bcb32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - pc-geoparquet = stac_geoparquet.cli:main

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - ciso8601
    - deltalake
    - geopandas
    - packaging
    - pandas
    - pyarrow >=16
    - pyproj
    - pystac
    - python >=3.8
    - shapely
    - orjson
    - typing-extensions

test:
  imports:
    - stac_geoparquet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/stac-geoparquet/
  summary: stac-geoparquet
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
    - TomAugspurger
