{% set name = "stac-geoparquet" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stac_geoparquet-{{ version }}.tar.gz
  sha256: 8c83752859e64104844b7c0226f269df1c5a6cfc610d9c505340be6e09996d9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - pc-geoparquet = stac_geoparquet.cli:main

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
  run:
    - ciso8601
    - ciso8601
    - deltalake
    - geopandas
    - packaging
    - pandas
    - pyarrow >=16
    - pyproj
    - pystac
    - shapely
    - orjson
    - typing-extensions  # [py<311]

test:
  imports:
    - stac_geoparquet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/stac-geoparquet/
  summary: stac-geoparquet
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
    - TomAugspurger
