{% set name = "stac-geoparquet" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stac_geoparquet-{{ version }}.tar.gz
  sha256: cc6f6a6c61d56811c265d603c9b13bcea65200c5714b5dbf59062a07ffa89289

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - pc-geoparquet = stac_geoparquet.cli:main

requirements:
  host:
    - pip
    - python >=3.8
    - flit-core
  run:
    - geopandas
    - pandas
    - pyarrow
    - pystac
    - python >=3.8
    - shapely

test:
  imports:
    - stac_geoparquet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/stac-geoparquet/
  summary: stac-geoparquet
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
    - TomAugspurger
